_target_: src.models.clipv1_module.ClipV1LitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0002
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  factor: 0.1
  patience: 10
  mode: min

eegnet:
  _target_: src.models.components.simple_atms.ATMS
  num_channels: ${channel_count:${data.selected_channels},63}
  sequence_length: 250
  num_subjects: 10
  nhead: 2
  num_layers: 1
  emb_size: 40
  emb_dim: 1440
  proj_dim: ${clip_dim:${data.model_name}}
  p: 0.5
  use_subject_embedding: ${is_cross_subject:${data.experiment_setting}}
  ts_filters: 40
  temporal_kernel: 25
  pool_kernel: 51
  pool_stride: 5

retrieval_k_list: [2, 4, 10, 200]
modality: eeg2img
loss_type: cliploss
alpha: 0.99

# compile model for faster training with pytorch 2.0
compile: false
