name: Code Quality PR

on:
  pull_request:
    branches: [main, "release/*", "dev"]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync --locked --extra cpu

      - name: Run pre-commit
        run: uv run --no-sync pre-commit run --all-files
